version: '3.8'

services:
  backend:
    container_name: ${APP_NAME?APP_NAME is required}-backend
    hostname: ${APP_NAME?APP_NAME is required}-backend
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      args:
        - BUILD_ENV=${BUILD_ENV}
